# Зашифрованные секреты стенда (SOPS + age) — ЭТОТ ФАЙЛ КОММИТИТСЯ.
# Редактирование:   sops helm/secrets/dev.yaml
# Расшифровка:      sops -d helm/secrets/dev.yaml
# Структура: блок `secrets` (см. helm/values.yaml) — шифруется целиком.
secrets:
    #ENC[AES256_GCM,data:YHeFt/mfiCFTn65qMcoS+PoOWxEyCJDp0IDgm2yrQptb5tjLeYbvWbr+8ddyGQiMF0uNEX8zDGAPwWtpp+k9q2LS7U0Klx1Cc6Y8rXE4Vae4CPsudGihubz+amAfdhvOy9O/ztkQNuoYBzaN6/ayXfXEREjoIWtugqfF8s0SBsV8b/U+wDmgx/EcYIZ6+tg1B78+,iv:xtMqu9KQQnhuvjvkbWsOrH2qTHPKQsFey1niXXYcW1U=,tag:Gu0TY3c+Xew2mkYS331iwQ==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:oYexyhSHX+F8nOwpUVVXpZ7ekZyQ/MIVeJbM9TuAbFFc9mhfWFI5PggulWZeOwgBtxEw,iv:YMl20+CRvab6CekE9sDKLaNyClU/Vfbsg75cINZtROc=,tag:NcKLZeLt98oMkzqcxhe3Ew==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:JVpmcqwCidYw8uHKS0MF9L9teMNQ3fL5,iv:wBdEMfuXIRcDa+SkSpoqrTKJ8k/U3CabMOogsa9zTb4=,tag:UKl3s0zIp9RxUNt9mg9ONA==,type:str]
    DB_ROOT_PASSWORD: ENC[AES256_GCM,data:T5yD0a+ekMe/TguwmvHXgfycFemYYR4C,iv:1DF/HUHIz0jgN8BK+SEfyKj694ZEQoh5usB1F6i6KT0=,tag:WvF4BVO4rSU44cXdoH4auA==,type:str]
    APP_URL: ENC[AES256_GCM,data:z42qlgzJDg/s4wsMhNJGx9mthsNWoQ==,iv:T5fkDNwJoZRtbaoonv1zqr1ss8qFhKD5JKGOGgGJ7e0=,tag:go01/l1H0pI0AFUfKlk3cA==,type:str]
    #ENC[AES256_GCM,data:Iq6vMZ/fpb4gqHBFfOnHB1+XgocAiwSwi/Z5Y5lWPjl5fOY+8+nDhejOJ8v4cHOn3Jgby5qry5TWsbXZYLeknblGzA5TA2TaxNQ8I/YJ3ARy+Stelbkgfal/JVw6V/LF40aEXsp3dGp0d2Bib2s=,iv:RbVSEaABRKhSzN6snwU23SQsxaOWlQp/Wp1ZdG8dXWM=,tag:YkPQw3BD4NROk4Q/Unyk3A==,type:comment]
    SMTP_HOST: ""
    SMTP_PORT: ENC[AES256_GCM,data:TIS6,iv:Sao6F2WrPOYEJ23W/KiBIIf3mXlyFlg8FE+2GjuY/K0=,tag:xHbquvBHFWNVagrwAL5bvg==,type:str]
    SMTP_USER: ""
    SMTP_PASS: ""
    SMTP_FROM: ""
    TO_EMAIL: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14l2l8qc9yhnzafpn2qq8f8y9tu8dq45drgyqlmh8dc0alnm579gsh93nfy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS3Z3OGJmVmJsa2VPdEtr
            TG56UktjRkM1T2Y2V0NldHB5NnkrTkVvdFhrCkFWdFBCemNJT2FZbkw4UkhZd0RY
            aGRtUm13V0pUMEcvdnFYUjRLM0RCc0UKLS0tIEpoVWs4dDlPVkZKQWFoZm1GV3lE
            blhIaW1uT2hjcXhnc0FNSjhLM1ZSeEkKGzlcKN4aRk5J1Yje21mqjQ3QFVsohZPM
            jrhhK8XkTvE1Z7/kLGg3qp6bpd+ULeZJqPq7PJK6U5GgiN6GoJ29CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T14:07:47Z"
    mac: ENC[AES256_GCM,data:d5ZoI+7YPnfq4iBZxtjl//CEt1yDnzGxphuWrz0Nb3tCOHCKOfSZ7tHrdEZJxO/bDc5PdtwW0e7fvDKVoKplBsAkgcUZG1ZMSjS//45nxdMIMXe182DxyD+jTX34zBqUFpm0KFcoMPhXEip3m31IMm+4A+9PFOhOspBVWq8t1zA=,iv:od9UIROyDcqT9s2ekg+9N+KX01rArvGFPsXla4hSloc=,tag:Bj+oePE4HL1Yx+K6f4/wiw==,type:str]
    pgp: []
    encrypted_regex: ^(secrets)$
    version: 3.9.4
